### ISSUE TITLE
Ipfw - Block - Problem

### ISSUE THREAD

**Issue by muchomor1337** [cyclaero/ipdb#3]
Hello sorry to write here but i'm new, can I get any contact for you? Eg discord.
I am trying to use your country blocker on ipfw but i dont know what am I doing wrong.

IPF="ipfw -q add"
ipfw -q -f flush
$IPF 100 allow all from any to any via em0
/usr/local/bin/ipup -t TR:SA:RU:GB -n 6 | /sbin/ipfw -q /dev/stdin
$IPF 70 deny all from table\(6\) to any via em0

I want to block countries, but always to no avail, because it cuts off everything at once instead of the ones listed here
Could you help me? Or explain something more what i am gone wrong

**Comment by muchomor1337** [comment]
overall i fixed it but could i have some additional contact please? I have a few questions

**Comment by cyclaero** [comment]
For the benefit of others interested in Geo blocking, please let us discuss your questions here.
