### ISSUE TITLE
Wrong location for IP adresses

### ISSUE THREAD

**Issue by herrbischoff** [cyclaero/ipdb#4]
### Environment

```
$ uname -a
FreeBSD [REDACTED] 13.0-RELEASE-p11 FreeBSD 13.0-RELEASE-p11 #0: Tue Apr  5 18:54:35 UTC 2022     root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
```

Used v1.1.2 from FreeBSD ports (https://www.freshports.org/sysutils/ipdbtools/) as well as manually compiled HEAD from this repository.

### Issue

While looking up certain IP addresses, the wrong country location is output.

Example (version compiled from HEAD):

```
$ ipup 195.68.58.17
195.68.58.17 -> 195.68.0.0 - 195.68.127.255 in GB
    net segment 195.68.0.0 - 195.68.127.255 owned by 64f7a1a7da9c4071b65e47b12db1922b
```

`ipup` locates the IP within GB, when in reality, it is located in the FR region. The [RIPE web lookup](https://apps.db.ripe.net/db-web-ui/query?searchtext=195.68.58.17) does output the correct location information.

**Comment by cyclaero** [comment]
The downloaded ripe data file is lacking the range 195.68.58.16 - 195.68.58.31, and therefore ipup cannot report the respective country code:

    grep "|195.68." /usr/local/etc/ipdb/IPRanges/ripencc.dat
    ripencc|GB|ipv4|195.68.0.0|32768|19960610|allocated|729f346b-5f0e-4e07-bc54-f9f0ca3058c3
    ripencc|RU|ipv4|195.68.128.0|16384|19990310|allocated|cd1831ac-25b9-4092-969f-441b078ad312
    ripencc|NL|ipv4|195.68.218.0|512|20191104|allocated|ae0398a9-047b-49ee-8233-fd1623f0c3c4
    ripencc|UA|ipv4|195.68.224.0|1024|20180604|allocated|fa7024ad-6ac1-4727-bb69-5ab2220bf067
    ripencc|FR|ipv4|195.68.248.0|512|20191104|allocated|4d11d811-5f47-47fd-ad4f-363bc18dabbd
    ripencc|FR|ipv4|195.68.254.0|512|20191104|allocated|4d11d811-5f47-47fd-ad4f-363bc18dabbd
    ripencc|PL|ipv4|195.68.192.0|512|20030513|assigned|f4947173-8f6a-4c2d-b1ab-4e13684231b6
    ripencc|FR|ipv4|195.68.194.0|512|20030514|assigned|c6fa7939-ddbd-463a-9ba6-521ffb3ec724
    ripencc|UA|ipv4|195.68.196.0|512|20030515|assigned|449783f5-d53a-4b3c-9310-98b0dbac6ccb
    ripencc|DE|ipv4|195.68.198.0|512|20030516|assigned|bb1681d4-a8b8-4dbf-a8f2-9b425166bdc1
    ripencc|BG|ipv4|195.68.200.0|512|20030520|assigned|c89cb234-ac18-45f1-9257-c79e40ed1ace
    ripencc|UA|ipv4|195.68.202.0|512|20030523|assigned|fae7e023-05e0-4aa4-a2c5-3f1c1d3c0536
    ripencc|DE|ipv4|195.68.204.0|512|20030526|assigned|4387fe5d-3758-47c6-bd87-731c4ac7c39b
    ripencc|GB|ipv4|195.68.206.0|512|20030526|assigned|e9ed9cf9-d1bf-4748-b60b-f67eda7df945
    ripencc|PS|ipv4|195.68.208.0|512|20040326|assigned|f1ae62a8-d5e3-4574-b9c2-339d9db3e51a
    ripencc|UA|ipv4|195.68.210.0|512|20030602|assigned|ffd62135-8349-4250-9667-7ee2d0890316
    ripencc|AT|ipv4|195.68.212.0|512|20030603|assigned|6bc77801-4a6d-4cd4-97ad-73ffd6f19019
    ripencc|BG|ipv4|195.68.214.0|512|20030604|assigned|5fe581e4-2294-4122-8db5-40aae9012fbc
    ripencc|UA|ipv4|195.68.216.0|512|20030606|assigned|d3c6bc72-5f9d-4f1b-ab28-6c58eaec4e8f
    ripencc|GB|ipv4|195.68.220.0|512|20030610|assigned|e9ed9cf9-d1bf-4748-b60b-f67eda7df945
    ripencc|UA|ipv4|195.68.222.0|512|20030612|assigned|e6f1901b-83ed-467e-ab7a-7817cb899d46
    ripencc|GB|ipv4|195.68.228.0|512|20030618|assigned|814df705-b0a4-45e3-801c-1c027f8e585e
    ripencc|SK|ipv4|195.68.230.0|512|20030618|assigned|725bc688-cf6d-4136-bb82-b9dcfcace48c
    ripencc|PL|ipv4|195.68.232.0|512|20030618|assigned|0b1fd29f-962d-4f34-838e-d1e48c125112
    ripencc|SK|ipv4|195.68.234.0|512|20030619|assigned|9be43ae4-cae6-4407-8431-081d22b16d96
    ripencc|DE|ipv4|195.68.236.0|512|20030623|assigned|474b2e83-198d-411b-85b8-097c2852e7fe
    ripencc|GB|ipv4|195.68.238.0|512|20030623|assigned|58909bc9-6517-4206-a78b-c41d4dd73f72
    ripencc|RU|ipv4|195.68.240.0|512|20110825|assigned|5996bc3f-13d5-416d-a9e8-2c1505bba369
    ripencc|DE|ipv4|195.68.242.0|512|20030624|assigned|6e683bb8-7cd3-465a-8751-1dc3ae013669
    ripencc|NL|ipv4|195.68.244.0|256|20110913|assigned|af53402d-a182-4192-abb6-d607bafefad3
    ripencc|RU|ipv4|195.68.245.0|256|20110913|assigned|3b750da7-1dfe-4e2a-98c9-f80445adedfb
    ripencc|DE|ipv4|195.68.246.0|512|20030701|assigned|d576bddc-51be-4174-b5cb-f454d7a84fb2
    ripencc|FR|ipv4|195.68.250.0|512|20030708|assigned|38863d92-edfe-4aa5-bf44-432c82dbcb1f
    ripencc|RU|ipv4|195.68.252.0|512|20030711|assigned|cc8dc417-ac8e-4612-bac2-fa801baf46bb

So nothing can be done about this in the ipdb-tools.

**Comment by arnaudpn** [comment]
Hi @cyclaero ,

I have a wrong result for 77.138.247.245:

root@icecube BSD:~ # ipup 77.138.247.245
77.138.247.245 in 77.128.0.0 - 77.159.255.255 in FR

A whois against the RIPE DB provides IL as country. 

I didn't check thoroughly but I guess the same reason as the one explained above applies for this case ?
