### ISSUE TITLE
ipdb-update.sh ftp.ripencc.net -  fetch: ftp://ftp.ripencc.net/pub/stats/afrinic/delegated-afrinic-extended-latest.md5: No address record

### ISSUE THREAD

**Issue by nikkadim** [cyclaero/ipdb#5]
`root@host:~# ipdb-update.sh ftp.ripencc.net
fetch: ftp://ftp.ripencc.net/pub/stats/afrinic/delegated-afrinic-extended-latest.md5: No address record

root@host:~# uname -a
FreeBSD CGP-II 12.1-RELEASE FreeBSD 12.1-RELEASE r354233 GENERIC  amd64 `

ipdbtools: 1.1.2_3

**Comment by cyclaero** [comment]
The FTP server of RIPENCC got the URL ftp.ripe.net and not ftp.ripencc.net. Pleas try again using the correct ftp URL.
